local DOCUMENT = {}

DOCUMENT.Name = "Leuonard"
DOCUMENT.Type = "Slasher"

DOCUMENT.Description = [[MONDAY NIGHT RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW]]
DOCUMENT.AdditionalDescription = [[MONDAY NIGHT RAAAAAAW]]

SlashCo.RegisterDocument(DOCUMENT)